# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rat < Formula
  desc ""
  homepage "https://github.com/Yakiyo/rat"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/rat/releases/download/v0.1.0/rat_Darwin_x86_64.tar.gz"
      sha256 "56d17b636b100262fe0288946ae8a1572c3ee31687fd3745261bf23d33695115"

      def install
        bin.install "rat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Yakiyo/rat/releases/download/v0.1.0/rat_Darwin_arm64.tar.gz"
      sha256 "e07ffc40230dd4bc8d9c0f34b09ac64e2cbb0b53575604cdc5ce738fb5051ff2"

      def install
        bin.install "rat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Yakiyo/rat/releases/download/v0.1.0/rat_Linux_arm64.tar.gz"
      sha256 "510a9ff3a31aa7dd781e866d40ce9a615c9391a26115c6ff5cc9ba32810ae708"

      def install
        bin.install "rat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Yakiyo/rat/releases/download/v0.1.0/rat_Linux_x86_64.tar.gz"
      sha256 "bad3e9dbb8d94f7d0fa69b7218d81ffaddf3c9a9a5556f57f21eb3ecb586e792"

      def install
        bin.install "rat"
      end
    end
  end
end
